### ISSUE TITLE
`lazy_static` is blocking

### ISSUE THREAD

**Issue by jeehoonkang** [crossbeam-rs/crossbeam-epoch#10]
As discussed in https://github.com/crossbeam-rs/crossbeam/pull/122#issuecomment-288436809, `lazy_static` is blocking.  It is used for the global registries, the garbage queue, and the global epoch.  It would be great if accessing them is non-blocking.

**Comment by arthurprs** [comment]
It's only blocking in the slow path due to Once, it only does a seqcst load on the fast-path  (https://github.com/rust-lang/rust/blob/c7104be1a37daa2f7ec114913247dc93524fd48e/src/libstd/sync/once.rs#L220)

**Comment by arthurprs** [comment]
Should we close this? (based on the above comment)

**Comment by jeehoonkang** [comment]
I feel we cannot easily change the current state of affair.  I'm closing this now, but please feel free to reopen it.
