### ISSUE TITLE
Can we think of a better name for `Garbage`?

### ISSUE THREAD

**Issue by jeehoonkang** [crossbeam-rs/crossbeam-epoch#12]
@stjepang said:

> "Garbage" is typically in plural and refers to a bunch of deleted/dead/unlinked objects. I'd prefer to use a better synonym in singular form. That said, I don't have any ideas for a better word to use. :)

@Vtec234 replied:

> It seems that such a word literally doesn't exist: [link](https://english.stackexchange.com/questions/240876/single-countable-word-for-trash-garbage). The closest name is PieceOfGarbage.

**Comment by jeehoonkang** [comment]
Maybe we can just call it `deferred`.  cf. https://github.com/crossbeam-rs/crossbeam-epoch/pull/15

**Comment by ghost** [comment]
Agreed. We don't really talk in terms of *garbage* anymore, but rather in terms of *deferred functions*.

**Comment by KasMA1990** [comment]
A singular piece of garbage could be a `scrap` maybe? I'd also be cautious about using `deferred` for its potential to be confusing in an async context in general, though I have no basis for actually calling if it's the right name or not :)

**Comment by jeehoonkang** [comment]
I'd like to suggest:

- Remove struct `Garbage` and use `Deferred` instead.  `Garbage` was actually just a thin wrapper around `Deferred`.  (In doing so, we need to change the semantics of `Deferred` a little bit: e.g. it should be `Sync + Send`.

- Move `Bag` in to `internal.rs`.  Note that it's not exposed to the `Collector` API.

While I like the name `Scrap`, I don't think we actually need it in the current implementation.  We can reintroduce `Garbage` (with a possibly better name) later when it is actually more than just a `Deferred`.

**Comment by ghost** [comment]
> In doing so, we need to change the semantics of `Deferred` a little bit: e.g. it should be `Sync + Send`.

I think this will conflict with the definition of `defer`, which doesn't require `Sync` nor `Send`. Remember, this decision was made to allow passing `Ptr` into the closure.
