### ISSUE TITLE
More impls for Ptr

### ISSUE THREAD

**Issue by ghost** [crossbeam-rs/crossbeam-epoch#22]
Since `Ptr` is just a pointer, it might make sense to implement `Eq` for it.

Currently, to compare whether two `Ptr`s are equal, one has to do: `a.as_raw() == b.as_raw()`. Why shouldn't we be able to do just `a == b`?

Maybe we could implement `Ord`, `Hash`, and `std::fmt::Pointer` as well.

**Comment by jeehoonkang** [comment]
I agree.  Also I don't think we need an RFC for this change.

**Comment by Vtec234** [comment]
Presumably we could just implement everything from [pointer](https://doc.rust-lang.org/std/primitive.pointer.html) that makes sense.
