### ISSUE TITLE
Handle should implement Clone

### ISSUE THREAD

**Issue by joshlf** [crossbeam-rs/crossbeam-epoch#24]
Without implementing `Clone`, users who wish to use a crossbeam `Handle` as part of their own handle-based design will need to ensure that they retain access to the original `Collector` so they can call `.handle()` on it to get a new `Handle`. With `Clone`, a user's handle-based implementation could be as simple as:

```rust
#[derive(Clone)]
struct MyHandle {
    gc: crossbeam_epoch::Handle,
}
```

**Comment by jeehoonkang** [comment]
Thanks!  I think it's a bug in #21.  I made a PR that corrects it (#26).  I also wrote a test function on `Handle::clone()`.

**Comment by joshlf** [comment]
Awesome, thanks!
