### ISSUE TITLE
Removing `from_*` methods

### ISSUE THREAD

**Issue by jeehoonkang** [crossbeam-rs/crossbeam-epoch#34]
e.g. as far as we implement `From<Owned<T>>` for `Atomic<T>`, `Atomic::from_owned()` is redundant.  I don't see much benefit of having these methods..

**Comment by ghost** [comment]
What about `Atomic::from_ptr` and `Owned::from_box`? Do you think we should remove those too?

One argument for keeping both `From<Foo>` impl and `fn from_foo` method is that the latter is more visible in the documentation. Readers of the documentation are often unware of all the available `From<Foo>` converters.

That said, we don't have to go overboard with too many `from_*` methods either. I'm okay with removing them.

**Comment by jeehoonkang** [comment]
Strangely, Rust compiler's type inference engine is not powerful enough for resolving `From`:

```rust
---- src/atomic.rs - atomic::Ptr<'g, T>::tag (line 1024) stdout ----
        error[E0283]: type annotations required: cannot resolve `crossbeam_epoch::Atomic<_>: std::convert::From<crossbeam_epoch::Owned<u64>>`
 --> src/atomic.rs:6:9
  |
6 | let a = Atomic::from(Owned::new(0u64).with_tag(5));
```

I had to write `Atomic::<u64>::from(Owned::new(0u64).with_tag(5))` to satisfy the compiler.  I think that's not that ergonomic..  If we cannot resolve this issue, let's keep the current interface..

**Comment by ghost** [comment]
Hmm, that's interesting. Although, this issue is unlikely to occur in practice because `Atomic`s are typically explicitly declared in `struct`s as full types. Inference problems only come up in toy examples like `let a = Atomic::from(...)`.

**Comment by Vtec234** [comment]
I suggest going forward with removing these methods and later if the type inference becomes a nuissance, adding them back. That's because doing so is a backwards-compatible change, but removing them later is not.
