### ISSUE TITLE
`cargo build` fails in Rust Nightly 1.24.0 (2017-11-27)

### ISSUE THREAD

**Issue by jeehoonkang** [crossbeam-rs/crossbeam-epoch#52]
```
$ rustc --version
rustc 1.24.0-nightly (560a5da9f 2017-11-27)

$ cargo build
   Compiling crossbeam-epoch v0.1.0 (file:///Users/jeehoon.kang/Works/crossbeam-epoch)
error[E0119]: conflicting implementations of trait `core::convert::Into<std::boxed::Box<_>>` for type `atomic::Owned<_>`:
   --> src/atomic.rs:732:1
    |
732 | / impl<T> Into<Box<T>> for Owned<T> {
733 | |     /// Converts the owned pointer into a `Box`.
734 | |     ///
735 | |     /// # Examples
...   |
748 | |     }
749 | | }
    | |_^
    |
    = note: conflicting implementation in crate `core`:
            - impl<T, U> core::convert::Into<U> for T
              where U: core::convert::From<T>;

error: aborting due to previous error

error: Could not compile `crossbeam-epoch`.

To learn more, run the command again with --verbose.
```

**Comment by ghost** [comment]
Looks like https://github.com/rust-lang/rust/issues/46328

**Comment by ghost** [comment]
Unfortunately, this error will persist. See [this comment](https://github.com/rust-lang/rust/issues/46328#issuecomment-347557526) for an explanation.

Let's bring back the explicit `into_box` method which we used to have a few weeks ago.

By the way, if you're worried that `into_box` might be unidiomatic, note that there are already several similar methods in the standard library:
https://doc.rust-lang.org/alloc/raw_vec/struct.RawVec.html#method.into_box
https://doc.rust-lang.org/collections/vec/struct.Vec.html#method.into_boxed_slice
https://doc.rust-lang.org/std/string/struct.String.html#method.into_boxed_str
