### ISSUE TITLE
Tsan reports data races on sanitize example

### ISSUE THREAD

**Issue by ordian** [crossbeam-rs/crossbeam-epoch#59]
Running
```
RUSTFLAGS="-Z sanitizer=thread" cargo +nightly run --example sanitize --target x86_64-unknown-linux-gnu
```
on current master ([36f7a36](https://github.com/crossbeam-rs/crossbeam-epoch/commit/36f7a36d122ec0565e796df22d80935b20eaecc5)) produces a lot of data race (in dealloc) [warnings](https://pastebin.com/vtYqVsDU).
[Same](https://pastebin.com/Z1BqeHE9) is true for running
```
RUSTFLAGS="-Z sanitizer=thread" cargo +nightly test --target x86_64-unknown-linux-gnu
```
on [this](https://github.com/ordian/lazy-transform-sync/blob/master/src/lib.rs) example.

**Comment by Vtec234** [comment]
This is because the garbage collector uses fences to guarantee correctness, which the thread sanitizer doesn't understand. Quoting @stjepang:

> Unfortunately, our code is full of fences, which thread sanitizer simply doesn't understand. I've noticed several false positives coming from thread sanitizer. The good news is that address sanitizer can still catch some errors due to bad memory orderings, incorrect epoch advancement, incorrect use of unprotected guards, etc.

**Comment by ordian** [comment]
Thanks! Closing the issue.
