### ISSUE TITLE
Undocumented/unused "strict_gc" feature

### ISSUE THREAD

**Issue by Thomasdezeeuw** [crossbeam-rs/crossbeam-epoch#66]
In `garbage.rs`, https://github.com/crossbeam-rs/crossbeam-epoch/blob/02c2c5953c1ab19db697cc6916f38d93d2550116/src/garbage.rs#L31-L35 a feature named "strict_gc" is used but is not documented anywhere. Is this a feature used when testing, or is this something that can be removed?

**Comment by jeehoonkang** [comment]
I'm proposing to remove this feature now, and revisit the issue of GC strictness later with a better solution.

**Comment by ghost** [comment]
This should actually be `#[cfg(feature = "sanitize")]` and is only used to trigger potential data races sooner than later. It's only meant to be used for testing/debugging.

@jeehoonkang How about we just fix this by replacing `strict_gc` with `sanitize`?

**Comment by jeehoonkang** [comment]
I agree with @stjepang.  Also a few lines of documentation will be much helpful!
