### ISSUE TITLE
0.4.2 contains a breaking change

### ISSUE THREAD

**Issue by jonas-schievink** [crossbeam-rs/crossbeam-epoch#79]
Updating `crossbeam-utils` to 0.4.0 is a breaking change since that version requires a newer version of Rust to compile (1.25 instead of 1.12). This has broken CI of one of my crates: https://travis-ci.org/jonas-schievink/xml-rpc-rs/jobs/391259820

As a side note, `.travis.yml` doesn't test for a minimum supported Rust version right now.

**Comment by ghost** [comment]
Oh. Sorry about that. :(

To fix this, I've just published `crossbeam-epoch` v0.4.3 that depends on `crossbeam-utils` v0.3. Now I'll specify the minimum version in the readme and add a check to `.travis.yml`.

Let me know if you run into any further issues and I'll fix them ASAP.

**Comment by jonas-schievink** [comment]
Thanks for the quick fix, my crate is working again!

The only additional thing you *could* do is yanking v0.4.2 from crates.io, just to *really* make sure nobody tries to use that version. Cargo will usually pick 0.4.3 over 0.4.2 anyway, so that's not strictly required.
