### ISSUE TITLE
Explain the meaning of `#[cold]` attribute for `fn try_advance()`

### ISSUE THREAD

**Issue by jeehoonkang** [crossbeam-rs/crossbeam-epoch#9]
reference: https://github.com/crossbeam-rs/crossbeam-epoch/blob/7c4ba5a1d7789cc2a6d40cafe5a9cc3dc8a72e16/src/epoch.rs#L36

It would be great to comment on this.

**Comment by arthurprs** [comment]
I'm curious as well, inline(never) is probably enough.

**Comment by ghost** [comment]
`#[cold]` lets the compiler know that this function is rarely executed in practice. The compiler then optimizes branches in favor of those that do not call cold functions.

For example, `pin` might occasionally (but rarely) call `try_advance`, but we want the compiler to place that call on a cold path. In other words, we want the compiler to optimize branching for the case when `try_advance` is not called.

**Comment by jeehoonkang** [comment]
Currently, `pin()` occcasionally calls `global::collect()` instead of `try_advance()`.  Would it be better to annotate `#[cold]` to `global::collect()` rather than `try_advance()`?

**Comment by jeehoonkang** [comment]
By the way, I hope we can annotate `#[cold]` to branches as well as functions, as we can in the Linux kernel (`unlikely(...)`).  But it appears we cannot do that today: https://doc.rust-lang.org/stable/reference/attributes.html#function-only-attributes

**Comment by arthurprs** [comment]
I think your observation (`global::collect()`) is correct @jeehoonkang

**Comment by ghost** [comment]
I agree -- we should probably annotate `global::collect` as `#[cold]`. However, I guess doesn't hurt to leave `try_advance` a `#[cold]` function as well. Advancement *is* a rare operation, after all.
